### ISSUE TITLE
Should add a warning sign regarding capitalization of words

### ISSUE THREAD

**Issue by yzheng710** [ArkEcosystem/ark-mobile#10]
I was trying to restore a wallet after generating a new address using the mobile wallet.

In Android, the keyboard automatically capitalize the first word. This minor error results in "restoring" a completely different wallet.

**Comment by alexbarnsley** [comment]
We will default to no capitalisation I think, since the default is no capitals at all

**Comment by erbogart28** [comment]
To add on: I think users should be alerted if the passphrase they entered does not import an existing wallet address, as opposed to having a new wallet generated by default if a passphrase is incorrect. Have seen quite a few confused user because of the lack of error prevention in this process.

**Comment by alexbarnsley** [comment]
I think that a new issue should be created for that @erbogart28
