### ISSUE TITLE
apple

### ISSUE THREAD

**Issue by Pedro-Souza** [ArkEcosystem/ark-mobile#101]
it's already done approved in apple store?

**Comment by alexbarnsley** [comment]
Not in the Apple store yet. It's been in their review process since our mobile app announcement. It's now out of our hands and in Apple's. Closing this as nothing more we can do other than wait.

**Comment by Pedro-Souza** [comment]
lol, I already published 1 app over there and delayed 2 days the review. tries cancel the build and resend

**Comment by boldninja** [comment]
@Pedro-Souza not as easy with finance and cryptocurrency apps, the review process is a lot more extensive and thorough with this (calls as well).

**Comment by alexbarnsley** [comment]
Cryptocurrency/Blockchain apps are considered "finance" which go under far stricter reviews than normal apps unfortunately. It's not they've not done anything. We've had updates from them saying they need time, etc to review.

**Comment by alexbarnsley** [comment]
Oh @boldninja replied xD

**Comment by Pedro-Souza** [comment]
Oh, true. So, good luck
