### ISSUE TITLE
Send transaction address field

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-mobile#106]
Can you guys come up with something so I can see the whole address when I scan a QR code? Currently I have to tap on the field and select/move it so I see how the address ends. Maybe if you remove the padding, the reset (X) button and/or move the QR icon...

**Comment by ItsANameToo** [comment]
What do you think of this:

![contacts](https://user-images.githubusercontent.com/35610748/37554851-d57a3f38-29de-11e8-9e1e-2a26356ba916.jpg)

It will add an ellipsis when the address is too long, but will show the full address when you press the input field (so you can still check the part of the address that was omitted).

**Comment by ItsANameToo** [comment]
@alexbarnsley @luciorubeens would something like this also be approved by you guys / the designer?

**Comment by alexbarnsley** [comment]
@ItsANameToo yes I think so. I'll ping Oleg!

**Comment by alexbarnsley** [comment]
@ItsANameToo we think we are happy with this. It's basically how the explorer is showing!  Could you do a PR for this to test? :Smiley

**Comment by Nasicus** [comment]
@ItsANameToo  do you know how to change the display name of the auto complete field? if not ping me on slack, I can tell you :)

**Comment by ItsANameToo** [comment]
@alexbarnsley you can test PR #118 

@Nasicus too late, already found it out by myself :P
