### ISSUE TITLE
Can't build the master repo

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/ark-mobile#122]
After the last merges, I can't `ionic cordova prepare` is failing:

```
Installing "cordova-plugin-statusbar" for ios
[ERROR] An error occurred while running cordova prepare (exit code 1).
```

Never had problems until now. Anyone else?

**Comment by ItsANameToo** [comment]
can you try to run `ionic cordova prepare --verbose` ? That should give more output when something goes wrong.
