### ISSUE TITLE
App hangs after changing pin code?

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/ark-mobile#132]
After changing your pincode (Settings \> Change PIN) it takes around 10-15 seconds before you get the message that it has been changed. During that time the app is unresponsive.

I'm wondering whether this is something on my end or if more people are experiencing this problem

**Comment by Nasicus** [comment]
I'm pretty sure this is behaving as expected.

When you change the pin code, it has to loop through all your profiles and all your wallets, decrypt the wallet passphrase, encrypt it with the new pin and store it again.

Depending on the number of wallets you have this will take quite a while.

But I think we should display a loading screen while this is happening, something like this (taken from `wallet-dashboard.ts`):

```
        const loader = this.loadingCtrl.create({
          content: `${translation}...`,
        });

        loader.present();
```

**Comment by ItsANameToo** [comment]
soon <sup>TM</sup>
