### ISSUE TITLE
Passphrase didn’t load correct wallet

### ISSUE THREAD

**Issue by DeadWelsh** [ArkEcosystem/ark-mobile#19]
I entered my passphrase into the iOS Ark mobile wallet, the Ark address doesn’t match the one on my desktop client. Any issues known? Do I have an incorrect passphrase? If so have I guessed someone else’s passphrase? I only have 1 wallet address AFAIK

**Comment by alexbarnsley** [comment]
@DeadWelsh this could likely be related to #10 - the first letter gets capitalised. just try entering it carefully, taking care of spaces and capitals

**Comment by alexbarnsley** [comment]
@DeadWelsh I'm going to close this issue as believed to be due to the capitalisation. If you continue to have problems, please ask in #help on Slack about importing a wallet and if that's not help then re-open this issue please.

**Comment by bag-man** [comment]
@alexbarnsley Can confirm the capitalisation issue, should definitely be fixed to make all input lowercase by default though.

**Comment by alexbarnsley** [comment]
It's already fixed and will be in the next release.
