### ISSUE TITLE
App freezes on QR Scan for iOS

### ISSUE THREAD

**Issue by erbogart28** [ArkEcosystem/ark-mobile#2]
Screen gives the error "there was a problem scanning QR code" immediately after trying to scan in, then the app freezes. Doesn't seem to access the camera. 

I'm currently on iOS 11.2.1

Importing with passphrase works just fine.

**Comment by Nasicus** [comment]
From the [release blog post](https://blog.ark.io/mobile-ark-wallet-a-wallet-for-everyone-aeb712d88e24):

> The QR scanner is not compatible with ‘Ionic View — Test Ionic Apps’ so it won’t work on iOS.
> This is currently a workaround as we are still waiting on approval from Apple (they are very strict with finance and cryptocurrency apps). When we get final approval for the iOS App store we’ll let you know via social channels.

**Comment by erbogart28** [comment]
Ah, I apologize. Actually just read that and came back here to make mention of that. Should I close this issue since it's already known?
