### ISSUE TITLE
QR scanner not working when sending

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-mobile#32]
OS: Android 5.1
Mobile wallet version: 1.0.0

Scanning a QR code doesn't work on the Send screen. I get this message:
_There was a problem scanning a QR code._

However, I have Barcode Scanner app and it worked from the first try.

And the message should be changed to:
_There was a problem scanning **the** QR code._

**Comment by alexbarnsley** [comment]
@zillionn where are you scanning the barcode from? Just so I can test this end

**Comment by zillionn** [comment]
![qrcode](https://user-images.githubusercontent.com/3462869/34523090-9a8ba0b6-f09e-11e7-9553-47c0e4caa3b2.png)
