### ISSUE TITLE
External links

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-mobile#34]
I believe all external links should open in the default browser not in the WebView. Can't see the whole URL, can't copy it...

![screenshot_2018-01-01-19-07-28](https://user-images.githubusercontent.com/3462869/34469460-0d192090-ef28-11e7-9c44-e537f63922d1.png)

**Comment by luciorubeens** [comment]
Weird, tested on iOS and it's opened direct on Safari. Can you check on android? @alexbarnsley

**Comment by alexbarnsley** [comment]
@luciorubeens my device does what the screenshot shows above. It's the in-app browser that's causing it. I thought it was intended functionality so never questioned it xD i will be back on mobile app tomorrow so will try and take a look, get it to use the default browser instead

**Comment by zillionn** [comment]
And by the way the "OPEN IN EXPLORER" link in the transaction details doesn't work for me.

**Comment by zillionn** [comment]
I believe the solution is to use target=_system:
inAppBrowser.create(url, "_system");

**Comment by alexbarnsley** [comment]
I didn't get round to taking a look today @zillionn. I mean you seem to know your way around, you could always make a PR and we help if you need any? Get yourself on the bounty ladder ;) if not, don't worry. I can take a look in the next few days for you

**Comment by zillionn** [comment]
If I was able to test the mobile app I would have tested this already...
