### ISSUE TITLE
Send All

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-mobile#35]
When use SEND ALL function I get this error message:
_**Not enough ARK on your account**_

The amount is 0.1 less than I have but still can't send them. Then I tried to send 0.2 less and got this error message:
**_Failed to validate transaction scheme: Expected type integer but found type number_**

I was able to send 0.3 less than my balance.

**Comment by Nasicus** [comment]
trying to reproduce this on DEVNET, but I can't. Where did you test this and on what device?
