### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-mobile#5]
Can't edit and/or delete contact.

**Comment by Highjhacker** [comment]
On a side note ; When I press "Edit" for a specific contact, I'm redirected on the edit form but the form itself is buggy. The value of the field "Name" is empty and the value of the field "Address" is the name of the contact. Like this :

![alt-text](https://i.imgur.com/2tn8vOV.png)

**Comment by alexbarnsley** [comment]
This has been resolved in #17
