### ISSUE TITLE
Add contact: Weird behaviors with existing contacts

### ISSUE THREAD

**Issue by Nasicus** [ArkEcosystem/ark-mobile#62]
There is some weird / wrong behavior when adding new contacts: 
- If you add a contact with an address which already exists, the existing contact is just updated, without any notice
  - Solution: Show an error instead, that a contact with that address already exists
- If you add a contact with a name of an existing contact and another address, it will create a new contact with the same name and a different address
  - Solution: Don't allow contacts with duplicate names (case insensitive) - show an error!

What do you guys think?
If you agree with me I will fix hat.

**Comment by alexbarnsley** [comment]
Yeh the address is used as the key for a contact. I think the only change to that would be to allow updating of the contact in a confirmation prompt or take the user to that contact instead of just throwing an error 👌

Agree with the contact name duplication

**Comment by Nasicus** [comment]
Ok I will show a prompt if an existing contact should be overwritten.

However I found another prolbem / confusion:

The contacts are often looked up and even edited "profile comprehensive".
What does this mean?

Let's say you have 2 DEVNET profiles, if you add a contact one one profile, it **won't** be added on the other profile. However if you happen to have a transaction where the address of the contact from the **other** profile appears, it will resolve to this contact name.

And even stranger: If you now create a new contact on the same problem with the same address, the other contact will not be affected, but once you edit the contact, the name will be changed on both profiles :trollface: 

My suggestion:
Only display / edit /add contacts on the CURRENT profile - never touch anything from other profiles.

**Comment by alexbarnsley** [comment]
I would consider that a bug. All profiles and the data within them should be separate. Changing in one profile should never change the others. Out of curiousity, if you change one, kill the app, then load the other profile, does the change still save?

**Comment by Nasicus** [comment]
Yes,

You can see pretty clear what's happening in this code block:

```
  editContact(address: string, contact: Contact) {
    if (lodash.isNil(this.profiles)) { return; }

    lodash.forEach(this.profiles, (item, id) => {
      if (item['contacts'][address]) {
        this.profiles[id]['contacts'][address] = contact;
      }
    });

    return this.saveProfiles();
  }
```

But in this case I will fix this all.
I will maybe even move all contact related stuff into an own service and use it where appropriate.
