### ISSUE TITLE
Wallet Backup: Don't show setting if no wallet is selected

### ISSUE THREAD

**Issue by Nasicus** [ArkEcosystem/ark-mobile#63]
When you entered a profile, go to the settings there is a "Wallet backup"  menu item. If you click it you get "please select a wallet first".

I suggest to simply not show the menu entry in the first place if no wallet is selected.¨
However since this looks like it was not just added "by accident" I wanted to ask first, if there's a specific reason this entry is always there.

**Comment by luciorubeens** [comment]
Well, I left this input just to users know that it's possible. But can be removed since #37 was implemented.

**Comment by Nasicus** [comment]
With removed you mean completely removed or only when no wallet is selected?
I suggest completely.

**Comment by luciorubeens** [comment]
Yeah, completely
