### ISSUE TITLE
[Bug][iOS] Sending transactions isn't working properly

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/ark-mobile#66]
Short video showing the problem:
https://streamable.com/s9stn

When I try to send a transaction, the wallet shows a loading animation, but it doesn't send the transaction.

**Comment by Nasicus** [comment]
Two questions:

1. Does it work in the Devnet?
2. Can you send without scanning the QR Code? (I.e. pasting in the address)

**Comment by vmunich** [comment]
Hehe, yeah I get the same bug when using the Devnet, also it doesn't matter if I scan a QR code or type the address myself, it still does the same loading animation and then nothing happens.

**Comment by Nasicus** [comment]
Hmm this works on my Android (at least with the current master,). Wonder if it's an iPhone related problem. If so someone else needs to verify & fix this.

**Comment by Pedro-Souza** [comment]
here on my android, this too worked normally.

**Comment by vmunich** [comment]
I pulled the latest master and the issue is gone somehow 😛 I did stumble on another issue though: https://github.com/ArkEcosystem/ark-mobile/issues/71
