### ISSUE TITLE
No support for second passphrases

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/ark-mobile#71]
At the moment, there's no support for second passphrases:

![Screenshot](https://i.gyazo.com/0d7bdcadfedc344d5adbae7285849879.png)

**Comment by Nasicus** [comment]
Second signature support is not integrated anywhere in the mobile app yet.
You can also not create a second signature via the UI.
I also saw this but guessed it's on purpose - not sure if they are already working on this feature or not, it's probably for them to answer :)

**Comment by ItsANameToo** [comment]
Actually, second passphrase works when voting for a delegate or registering as a delegate yourself, as you get a modal to fill in your second passphrase. I already asked @luciorubeens about why this is not enabled when sending a transaction, so awaiting a reply on that

**Comment by Nasicus** [comment]
Oh really. Sorry for the misinformation then @vmunich. Was for some reason sure that it's not yet used (in the UI) anywhere :D
Thanks for the correction @ItsANameToo !
