### ISSUE TITLE
Proposal: Wallets vs Read-only Wallets vs Contacts

### ISSUE THREAD

**Issue by Nasicus** [ArkEcosystem/ark-mobile#79]
This topic could also have been opened in [ark-desktop](https://github.com/ArkEcosystem/ark-desktop), however since I will probably implement something related to this on mobile first, I opened it here.

# Definitions

First let's define how I see the three different types which in my opinion should exist.

## Wallet (account)
A normal wallet is an address I own, where I have the private key _and_ I imported this wallet via the private key _or_ verified in the app with the private key that this is my wallet.

**=> should appear in the "My Wallet" list**

I also think it would be good if we would use the same term in all products (in ark-desktop we're using account). I guess **wallet** will be the choice here?

## Watch-only wallet (watch-only account)
A read only wallets is an address which I _claim_ or _know_ I own because I also have the private key, but I don't _want_ to type / import the private key - at any point - in the app. This wallet is imported by it's public address or public key.

**=> should appear in the "My Wallet" list**

Of course this wallet should have reduced functionality. Actions like send, vote, etc. should be hidden, basically it's treated almost like a contact.

For a read-only wallet we should instead offer the option `Convert to full wallet` (or what ever), where you can then enter your private key to verify it's really your own and the send, vote, etc. actions will appear.

## Contact

A contact is an address which I connect with a name. The address (normally) doesn't belong to me. Maybe I send Ark to it often or get Ark from it often. In any case: I just want to put a name to an address. I don't care about the balance or anything else on it.

**=> should NOT appear in the "My Wallet" list, but instead appears in a contact list**

A contact doesn't have any actions at all. You also can't convert it to a wallet.

### Watch-only wallet vs Contact
In my opinion from a user perspective these are _different things_ and should be kept apart, even when the two of them are very similar from a programming / logic standpoint.

# Ark Desktop

As far as I know in ark-desktop at some points the functionality of "watch-only wallets (accounts)" was replaced by "contacts". I must admin: I don't like that - for the reasons above. 
I personally would at some point refactor & change this again.
Also I would rename all "account" related stuff to "wallet".

# Ark Mobile

At the moment we only have **wallets** and **contacts**.
I'd like to add the functionality of watch-only wallets to the app because I think it would be a great addition and I'm pretty sure I'm not the only one who doesn't want to enter his real private key to a mobile app (no matter how securely it is encrypted).

## Implementation

Roughly said I would do it like this:
- When importing wallets, offer the possibility to either enter or scan addresses _or_ private keys. 
  - Depending on what was scanned show to the user what is gonna be created / imported.
- Display Watch-Only wallets with a different color in the wallet list
- Display the wallet type somewhere (`is watch only`) or something like this
- Hide all actions which require a private key
- Show an action `Convert to full wallet` (or something similar)
  - I personally would even like the possibility to _not_ save & encrypt the private key and just re-enter it every time when I need it (but that can be done in a second step)

----------

I didn't start with this yet, because I wanted to discuss this first and hear your opinions about it.

So: What are your opinions about all of this?

**Comment by luciorubeens** [comment]
Well, watch-only addresses has been implemented. It's exactly the same thing as read-only 🤔

**Comment by Nasicus** [comment]
Haha I knew I remembered seeing something with `...only` but only searched for `read-only` before writing this post.
Need to try this out then.
(but the rest of this post is still valid :D )

**Comment by luciorubeens** [comment]
I think you drank some wine today 🍷🤣

The only thing I saw that has not yet been implemented is the last item: `Convert to full wallet`.

If you import your address by QR Code the wallet will be watch-only, but in order to "convert to full wallet" you must go on the screen to import and enter your passphrase.

About `ark-desktop`, yes! we should use `wallet` instead of `account`.

**Comment by alexbarnsley** [comment]
@Nasicus did this get resolved with your Pull Request? 🤔

**Comment by Nasicus** [comment]
Yes I think so.
Let's close this.
(We / you need imho just to see that the naming etc. will be the same in the new ark-desktop ;) )
