### ISSUE TITLE
Exit -> Sign out

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-mobile#83]
Don't you think the "Exit" button should be renamed to "Sign out"? You're not exiting the app by tapping it, you're actually signing out.

**Comment by zillionn** [comment]
Also when I tap back, I believe the confirmation should say "Sign out of profile?.

**Comment by luciorubeens** [comment]
I agree

**Comment by zillionn** [comment]
@Nasicus can you do this change?

**Comment by Nasicus** [comment]
Of course. Will do it tomorrrow :)
