### ISSUE TITLE
Delegates issue

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/ark-mobile#86]
This was reported by "Themuller" on Slack.

A vote was placed from within the mobile app (Android). This transaction has gone through successfully and can be seen on the explorer. The problems comes when viewing the vote on the Delegates list. The list of Delegates is empty, resulting in the "Could not fetch current vote" toast error message. Here's a screenshot:

![image](https://user-images.githubusercontent.com/8069294/36865757-5cc5b566-1d88-11e8-9ac1-91e5641d5c3d.png)

![image](https://user-images.githubusercontent.com/8069294/36865808-7f877e36-1d88-11e8-95da-ed4cbe054eed.png)

**Comment by Nasicus** [comment]
I cannot reproduce this on Android.

Tried voting for a delegate in the top 51 => works.
Voting for one outside of top 51=> works.

When I close the app go back to the delegates list, it shows the delegates + my voted delegate correctly.

**Comment by alexbarnsley** [comment]
@Nasicus yeh I wasn't able to reproduce either. It also fixed itself for Themuller. I will close unless we have more reporting. It could have been a bad peer at the time.

**Comment by xthexpert** [comment]
I'm on iOS, exact issue is happening to me. Explorer looks great. Moreover, total balance within the app is not updating. When selecting "change peer" from the "network status" page, it does not appear to change after the "looking for a good peer" prompt ends.

**Comment by FloryanFilip** [comment]
Firstly installed app somewhere in 2017. Voted for delegate jarunik back then.
Fast forward to today, I open the app and can tell that my last delegate payout was 10months ago. I wanted to vote for a new delegate to find what is documented below.
![ezgif com-crop](https://user-images.githubusercontent.com/23243818/55482165-389aef00-5624-11e9-89b8-d2859c4d9bca.gif)
