### ISSUE TITLE
NaN for equivalentAmount (transactions)

### ISSUE THREAD

**Issue by dahfsvcsbajfdryg** [ArkEcosystem/ark-mobile#9]
Android Nougat - Galaxy S7 
![26142332_3894093507019_156968717_o](https://user-images.githubusercontent.com/34894613/34391781-e089afd8-eb15-11e7-8613-1b687c0d627f.jpg)

**Comment by alexbarnsley** [comment]
@dahfsvcsbajfdryg is this still happening for you? Are you able to reproduce, as I'm struggling to get the same result you are. Did you have data enabled, etc? thanks

**Comment by dahfsvcsbajfdryg** [comment]
I think you're right! I think it had to do with Internet connection at the time, sorry Mr. Barnsley.
