### ISSUE TITLE
Strange little square

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-mobile#92]
On some pages like Settings, Network Status, Contacts, there is this little grey square in the top left corner:

![screenshot_20180303-171800](https://user-images.githubusercontent.com/3462869/36935971-6d54d3f0-1f07-11e8-9e59-c54f0f896c57.png)

![screenshot_20180303-171811-1](https://user-images.githubusercontent.com/3462869/36935972-70334822-1f07-11e8-9bc6-e362acfef35d.png)

What the heck is this??? :)

**Comment by ItsANameToo** [comment]
It's a small scrollbar. Some views don't have enough content to scroll, but Ionic still shows the scrollbar on those pages. I'll take a look into it, as I believe it can be fixed with a little css

**Comment by Pedro-Souza** [comment]
Hi @ItsANameToo
`.scroll-content{
     overflow-y:auto; 
} `fix this, i guess

**Comment by ItsANameToo** [comment]
@Pedro-Souza correct! The only issue is that on iOS you would want to have `overflow-y: scroll`, as that will give a "momentum" feel to to it. By setting it to `auto;` this momentum will be removed on pages that don't have enough content to scroll, so I'm looking into a way to keep this on iOS. I think it should work when using the following:

```
.content .scroll-content {
    overflow-y: auto;
}
.content-ios .scroll-content {
    overflow-y: scroll;
}
```

**Comment by Pedro-Souza** [comment]
Yes, I think it should resolve
